# Generated by Django 4.2.11 on 2025-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='questions',
            field=models.JSONField(default=dict),
        ),
    ]
